dist: trusty
language: ruby
cache:
  directories:
    - node_modules
  yarn: true
bundler_args: --without production
install:
  - nvm install node 12.12.0
  - nvm use 12.12.0
  - npm i -g yarn
  - npm i -g codecov
  - yarn
before_script:
  - gem install brakeman
  - gem install bundler-audit
script:
  - SKIP_PENDING=true bundle exec rake
  - yarn jest --verbose=false
  - codecov
  - brakeman -q
  - bundle audit --update
services:
  - mongodb
