dist: trusty
language: ruby
rvm:
 - 2.5.7
cache:
  bundler: true
  directories:
    - node_modules
  yarn: true
install:
  - bundle install
  - nvm install node 12.12.0
  - node -v
  - npm i -g yarn
  - npm i -g codecov
  - yarn
before_script:
  - gem install brakeman
  - gem install bundler-audit
script:
  - SKIP_PENDING=true bundle exec rake
  - yarn jest --verbose=false
  - codecov
  - brakeman -q
  - bundle audit --update
services:
  - mongodb
