dist: trusty
language: ruby
rvm:
 - 2.5.1
cache:
  bundler: true
  directories:
    - node_modules
  yarn: true
before_install:
  - gem install bundler
install:
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn
script:
  - bundle exec rails webpacker:compile
  - bundle exec rake
services:
  - mongodb
