dist: trusty
language: ruby
cache:
  directories:
    - node_modules
  yarn: true
  bundler: true
env:
  - MONGODB=4.0.4
install:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGODB}.tgz
  - tar xzf mongodb-linux-x86_64-${MONGODB}.tgz
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --version
  - nvm install node
  - nvm use node
  - node -v
  - npm i -g yarn
  - npm i -g codecov
  - yarn
  - bundle install --deployment --with test --jobs=3 --retry=3
before_script:
  - gem install brakeman
  - gem install bundler-audit
  - mkdir ${PWD}/mongodb-linux-x86_64-${MONGODB}/data
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --dbpath ${PWD}/mongodb-linux-x86_64-${MONGODB}/data --logpath ${PWD}/mongodb-linux-x86_64-${MONGODB}/mongodb.log --fork
script:
  - SKIP_PENDING=true IS_BETA=true bundle exec rake
  - yarn jest --verbose=false
  - codecov
  - brakeman -q
  - bundle audit --update
