dist: trusty
language: ruby
cache:
  directories:
    - node_modules
  yarn: true
  bundler: true
install:
  - npm i -g yarn
  - npm i -g codecov
  - yarn
  - bundle install --deployment --with test --jobs=3 --retry=3
before_script:
  - gem install brakeman
  - gem install bundler-audit
script:
  - SKIP_PENDING=true bundle exec rake
  - yarn jest --verbose=false
  - codecov
  - brakeman -q
  - bundle audit --update
services:
  - mongodb
