dist: trusty
language: ruby
cache:
  directories:
    - node_modules
  yarn: true
  bundler: true
bundler_args: --without production --jobs=3 --retry=3
before_install:
  - gem install bundler
install:
  - nvm install 12.12.0
  - nvm use 12.12.0
  - npm i -g yarn
  - npm i -g codecov
  - yarn
  - bundle install
before_script:
  - gem install brakeman
  - gem install bundler-audit
script:
  - SKIP_PENDING=true bundle exec rake
  - yarn jest --verbose=false
  - codecov
  - brakeman -q
  - bundle audit --update
services:
  - mongodb
