dist: trusty
language: ruby
rvm:
 - 2.5.1
cache:
  bundler: true
  directories:
    - node_modules
  yarn: true
before_install:
  - gem install bundler
install:
  - bundle install --without production
  - nvm install node
  - node -v
  - npm i -g yarn
  - npm i -g codecov
  - yarn
before_script:
  - gem install brakeman
  - gem install bundler-audit
script:
  - bundle exec rails webpacker:compile
  - bundle exec rake
  - yarn jest
  - codecov
  - brakeman
  - bundle audit --update
services:
  - mongodb
